src/Entity/Galery.php
<?php

namespace App\Entity;

use App\Repository\GaleryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GaleryRepository::class)
 */
class Galery
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedDate;

    /**
     * @ORM\OneToMany(targetEntity=SubGalery::class, mappedBy="galery", orphanRemoval=true)
     */
    private $subGaleries;

    public function __construct()
    {
        $this->subGaleries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->CreatedDate;
    }

    public function setCreatedDate(\DateTimeInterface $CreatedDate): self
    {
        $this->CreatedDate = $CreatedDate;

        return $this;
    }

    /**
     * @return Collection|SubGalery[]
     */
    public function getSubGaleries(): Collection
    {
        return $this->subGaleries;
    }

    public function addSubGalery(SubGalery $subGalery): self
    {
        if (!$this->subGaleries->contains($subGalery)) {
            $this->subGaleries[] = $subGalery;
            $subGalery->setGalery($this);
        }

        return $this;
    }

    public function removeSubGalery(SubGalery $subGalery): self
    {
        if ($this->subGaleries->removeElement($subGalery)) {
            // set the owning side to null (unless already changed)
            if ($subGalery->getGalery() === $this) {
                $subGalery->setGalery(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->getName();
    }

}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\Newletters\Users;
use App\Form\CategoryGaleryType;
use App\Form\ContactType;
use App\Form\NewsLettersUsersType;
use App\Repository\AlbumsRepository;
use App\Repository\ArticlesRepository;
use App\Repository\CategoryRepository;
use App\Repository\EquipeRepository;
use App\Repository\GaleryRepository;
use App\Repository\JoueursRepository;
use App\Repository\MatchAVenirRepository;
use App\Repository\SubGaleryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="accueil", methods={"POST","GET"})
     */
    public function index(Request               $request,
                          MatchAVenirRepository $nextMatchRepository,
                          ArticlesRepository    $articlesRepository,
                          CategoryRepository    $categoryRepository): Response
    {
        // le dernier article publié
        $articlePremier = $articlesRepository->findLast();
        // la liste des match a venir
        $prochainMatch = $nextMatchRepository->findAllMatchToPlay();

        // les categories qui ont des articles
//        $categoryArticles = $categoryRepository->findAllCategory();
        $categoryArticles = $categoryRepository->findAllCategoryWithArticles();

        //les articles des info-club
        $articleInfoDuClub = $articlesRepository->findByCategoryInfoClub('Info-Club');
        $user = new Users();
        $form = $this->createForm(NewsLettersUsersType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $token = hash('sha256', uniqid());
            $user->setCreatedDate(new \DateTime('now'));
            $user->setValidationToken($token);
            $user->setIsValid(0);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('accueil');
        }

        if ($request->isXmlHttpRequest()) {
//            recup de la catégorie
            $categoryAjax = $request->get('category');
            // reponse ajax de l'article dans la catégories affichée
            $article = $articlesRepository->findByCategory($categoryAjax);
            $titre = $article->getTitre();
            $date = $article->getCreatedDate();
            $date =
            $date = date_format($article->getCreatedDate(),'Y-m-d');
            $datestring = explode('-',$date);
//            $date = $article->getCreatedDate()->date_format('m-d-Y H:s');
            $slug = $article->getSlug();
            $image = $article->getPhotoEnAvant()->getName();
            return new Jsonresponse([
                'nextmatch' => $prochainMatch,
                'titre' => $titre,
                'annee' => $datestring[0],
                'mois'=>$datestring[1],
                'jour'=>$datestring[2],
                'slug' => $slug,
                'image' => $image,

            ]);
        }

        return $this->render('main/index.html.twig', [
            'articlePremier' => $articlePremier,
            'articleInfo' => $articleInfoDuClub,
            'category' => $categoryArticles,
            'nextmatch' => $prochainMatch,
            'form' => $form->createView()

        ]);
    }


    /**
     * @Route("/equipe/{id}", name="main_equipe")
     */
    public function equipe($id, Request $request, EquipeRepository $equipeRepository, CategoryRepository $categoryRepository): Response
    {
        if ($request->isXmlHttpRequest()) {
            $categoryAjax = $request->get('category');
            $equipe = $equipeRepository->findAllTeam($categoryAjax);
            return new Jsonresponse([
                'equipe' => $equipe,
            ]);
        }

        $user = new Users();
        $form = $this->createForm(NewsLettersUsersType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $token = hash('sha256', uniqid());
            $user->setCreatedDate(new \DateTime('now'));
            $user->setValidationToken($token);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }


        $category = $categoryRepository->findAllCategory();
        if ($id == 'autres') {
            $equipe = $equipeRepository->findAllTeam();
            return $this->render('main/autresEquipe.html.twig', [
                'equipe' => $equipe,
                'category' => $category,
                'form' => $form->createView()
            ]);
        }

        $cattocompare = $categoryRepository->findAllCategory();
        if ($this->compare($id, $cattocompare)) {

            $equipe = $equipeRepository->findotherTeam($id);

            return $this->render('main/autresEquipe.html.twig', [
                'equipe' => $equipe,
                'category' => $category,
                'form' => $form->createView()
            ]);
        } else {
            $equipe = $equipeRepository->findEquipe($id);
        }
        return $this->render('main/equipe.html.twig', [
            'equipe' => $equipe,
            'form' => $form->createView()
        ]);
    }
    public function compare($id, $cattocompare)
    {
        foreach ($cattocompare as $cat) {
            if ($id == $cat) {
                return true;
            }
        }
    }

    /**
     * @Route("/joueur/{id}", name="main_joueur")
     */
    public function joueurView(Request $request,$id, JoueursRepository $joueursRepository){
        $joueur = $joueursRepository->find($id);
        $user = new Users();
        $form = $this->createForm(NewsLettersUsersType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $token = hash('sha256', uniqid());
            $user->setCreatedDate(new \DateTime('now'));
            $user->setValidationToken($token);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }
        return $this->render('main/joueur.html.twig',[
            'joueur'=>$joueur,
            'form'=>$form->createView()
        ]);

    }


    /**
     * @Route("/main/albums/view{id}", name="main_albums_view")
     */
    public function albumsView($id, Request $request, AlbumsRepository $albumsRepository): Response
    {
        $albums = $albumsRepository->find($id);

        if ($request->isXmlHttpRequest()) {
            $imageHasard = $albumsRepository->findAPhoto($request->get('image'));
            $image = $imageHasard['name'];
            return new Jsonresponse([
                'image' => $image,
            ]);
        }

        $user = new Users();
        $form = $this->createForm(NewsLettersUsersType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $token = hash('sha256', uniqid());
            $user->setCreatedDate(new \DateTime('now'));
            $user->setValidationToken($token);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }
        return $this->render('main/albumsView.html.twig', [
            'form' => $form->createView(),
            'albums' => $albums,
        ]);
    }

    /**
     * @Route("/main/albums{id}", name="main_albums")
     */
    public function albums($id, Request $request, AlbumsRepository $albumsRepository): Response
    {
        $albums = $albumsRepository->findMainAlbumParSousCategory($id);

        if ($request->isXmlHttpRequest()) {
            $imageHasard = $albumsRepository->findAPhoto($request->get('image'));
            $image = $imageHasard['name'];
            return new Jsonresponse([
                'image' => $image,
            ]);
        }

        $user = new Users();
        $form = $this->createForm(NewsLettersUsersType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $token = hash('sha256', uniqid());
            $user->setCreatedDate(new \DateTime('now'));
            $user->setValidationToken($token);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }
        return $this->render('main/albums.html.twig', [
            'form' => $form->createView(),
            'albums' => $albums,
        ]);
    }

    /**
     * @Route("/sous/galerie{id}", name="sous_galerie")
     */
    public function subGalery($id, Request $request, SubGaleryRepository $subGaleryRepository): Response
    {
        $sousGalery = $subGaleryRepository->findMainSousGalerieParCategory($id);

        if ($request->isXmlHttpRequest()) {
            $imageHasard = $subGaleryRepository->findAPhoto($request->get('image'));
            $image = $imageHasard['name'];
            return new Jsonresponse([
                'image' => $image,
            ]);
        }

        $user = new Users();
        $form = $this->createForm(NewsLettersUsersType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $token = hash('sha256', uniqid());
            $user->setCreatedDate(new \DateTime('now'));
            $user->setValidationToken($token);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }
        return $this->render('main/subGalery.html.twig', [
            'form' => $form->createView(),
            'subGalery' => $sousGalery,
        ]);
    }


    /**
     * @Route("/galerie", name="galerie")

templates/main/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}about{% endblock %}

{% block body %}
  <h3>coucou</h3>
    <a href="{{ path('main') }}">acceuil main</a>



{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('css/_article.css') }}">
  <link rel="stylesheet" href="{{ asset('css/login.css') }}">
  <link rel="stylesheet" href="{{ asset('css/main.css') }}">
  <link rel="stylesheet" href="{{ asset('css/_index.css') }}">
  <link rel="stylesheet" href="{{ asset('css/_legals.css') }}">

{% endblock %}

templates/main/actualite.html.twig
{% extends 'baseMain.html.twig' %}

{% block title %}FCE Merignac Arlac{% endblock %}
{% block meta %}

    <meta name="description" content="{{ article.metaDescription }}">
{% endblock %}
{% block body %}
    {{ include('include/_mainNavigation.html.twig') }}
    <main>

        <section class="display">
            <img src="{{ asset('/uploads/'~article.photoEnAvant.name) }}" alt="" />
            <div class="link title">
                <h2>{{ article.titre }}</h2>
                <div class="interaction">
                    {{ article.createdDate |date('d / m / Y')}}
{#                  |  Partager l'article#}
{#                    <svg#}
{#                            viewBox="0 0 24 24"#}
{#                            width="20"#}
{#                            height="20"#}
{#                            stroke="currentColor"#}
{#                            stroke-width="2"#}
{#                            fill="none"#}
{#                            stroke-linecap="round"#}
{#                            stroke-linejoin="round"#}
{#                    >#}
{#                        <circle cx="18" cy="5" r="3"></circle>#}
{#                        <circle cx="6" cy="12" r="3"></circle>#}
{#                        <circle cx="18" cy="19" r="3"></circle>#}
{#                        <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line>#}
{#                        <line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line>#}
{#                    </svg>#}
                </div>
                <p>{{ article.introduction }}</p>
            </div>
        </section>
        <section class="content container">
            <p class="text">{{ article.contenu|raw }}
            </p>
            {% if article.equipe.name != 'Info-Club' %}
            <a href="{{ path('main_equipe',{id : article.equipe.name}) }}" class="btn btn-secondary">
                Voir l'équipe
            </a>
            {% endif %}
        </section>
        <section class="photos">
            <div class="img-container">
                {% for photo in article.photoFond %}
                <img src="{{ asset('/uploads/'~photo.name) }}" alt="" />
                {% endfor %}
            </div>
        </section>
    </main>


{{ include('include/mainFooter.html.twig') }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/_article.css') }}">
    <link rel="stylesheet" href="{{ asset('css/login.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_index.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_legals.css') }}">

{% endblock %}

templates/main/equipe.html.twig
{% extends 'baseMain.html.twig' %}
{% block title %}Equipes{% endblock %}
{% block body %}
    {% include 'include/_mainNavigation.html.twig' %}
    <main>
        <section class="pageequipes">

            {% if equipe.photoEquipe != null %}
                <img src="{{ asset('uploads/'~equipe.photoEquipe) }}" alt=""/>
            {% endif %}
            <div class="bandeau">
                <div class="h1bandeau">
                    <h1>{{ equipe.name }}</h1>
                </div>
                <div class="href">
                    <a href="#joueur">La composition de l'équipe</a>
                    <a href="#resultat">Ses résultats</a>
                    <a href="#actu">Ses dernières actualités</a>
                </div>
            </div>
        </section>
        <section class="title-composition">
            <h2>La composition de l'équipe</h2>
        </section>
        <section id="joueur" class="">
            <div class="photo-joueur">
                {% if equipe.joueurs is not empty %}
                    {% for joueur in equipe.joueurs %}
                        {% if joueur.poste == 'Gardien' or joueur.poste == 'Gardienne' %}
                            <a href="{{ path('main_joueur',{id: joueur.id}) }}">
                                <img style="max-width:389px; max-height:386px;"
                                     src="{{ asset('uploads/'~joueur.photoPortrait) }}"
                                     alt=""/>
                                <div class="title-game">
                                    <h3>{{ joueur.lastname }} {{ joueur.name }}</h3>
                                    <span class="date">{{ joueur.poste }}</span>
                                </div>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% for joueur in equipe.joueurs %}
                        {% if joueur.poste == 'Défenseur' or joueur.poste == 'Défenseuse' %}
                            <a href="{{ path('main_joueur',{id: joueur.id}) }}">
                                <img style="max-width:389px; max-height:386px;"
                                     src="{{ asset('uploads/'~joueur.photoPortrait) }}"
                                     alt=""/>
                                <div class="title-game">
                                    <h3>{{ joueur.lastname }} {{ joueur.name }}</h3>
                                    <span class="date">{{ joueur.poste }}</span>
                                </div>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% for joueur in equipe.joueurs %}
                        {% if joueur.poste == 'Milieu' %}
                            <a href="{{ path('main_joueur',{id: joueur.id}) }}">
                                <img style="max-width:389px; max-height:386px;"
                                     src="{{ asset('uploads/'~joueur.photoPortrait) }}"
                                     alt=""/>
                                <div class="title-game">
                                    <h3>{{ joueur.lastname }} {{ joueur.name }}</h3>
                                    <span class="date">{{ joueur.poste }}</span>
                                </div>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% for joueur in equipe.joueurs %}
                        {% if joueur.poste == 'Attaquant' or joueur.poste == 'Attaquante' %}
                            <a href="{{ path('main_joueur',{id: joueur.id}) }}">
                                <img style="max-width:389px; max-height:386px;"
                                     src="{{ asset('uploads/'~joueur.photoPortrait) }}"
                                     alt=""/>
                                <div class="title-game">
                                    <h3>{{ joueur.lastname }} {{ joueur.name }}</h3>
                                    <span class="date">{{ joueur.poste }}</span>
                                </div>
                            </a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </section>
        <section id="resultat" class="resultats-equipes">
            <h2>Les résultats de l'équipe</h2>
            {% if equipe.scriptResultat is not empty %}
                {{ equipe.scriptResultat| raw }}
            {% else %}
                <p>Aucun résultat pour le moment</p>
            {% endif %}
        </section>
        <section id="actu" class="resultats-equipes">
            <div><h2>Les actualités de l'équipe</h2></div>
            <div class="actuequipe">
                {% for article in equipe.articles |slice(0,3) %}

                    <a href="{{ path('article_slug',{slug : article.slug}) }}">
                        <img style="max-width:561px; max-height:386px;"
                             src="{{ asset('uploads/'~article.photoEnAvant) }}">
                        <div class="title-game" style="width: 80%">
                            <h3> {{ article.titre }}</h3>
                            <span>publié le: {{ article.createdDate |date('d-m-Y') }}</span>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </section>

    </main>
    {{ include('include/mainFooter.html.twig') }}
    <script type="text/javascript" src="app.js"></script>
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/_article.css') }}">
    <link rel="stylesheet" href="{{ asset('css/login.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_index.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_legals.css') }}">
    <link rel="stylesheet" href="{{ asset('css/.equipe.css') }}">
{% endblock %}

templates/main/index.html.twig
{% extends 'baseMain.html.twig' %}

{% block title %}FCE Merignac Arlac{% endblock %}

{% block body %}
    {% include 'include/_mainNavigation.html.twig' %}
    <main>
        <section class="actus">
            <a href="{{ path('article_slug',{'slug': articlePremier.slug}) }}" class="last-actu">
                <h3>Dernières actualités</h3>
                {% if articlePremier.photoEnAvant != null %}
                    <img src="{{ asset('uploads/'~ articlePremier.photoEnAvant.name ) }}" alt=""/>
                {% endif %}
                <div class="link title">
                    <h3>{{ articlePremier.titre }}</h3>
                    <span class="date">{{ articlePremier.createdDate|date('d / m / Y') }}</span>
                </div>
            </a>
            {% if nextmatch != null and nextmatch|length == 2 %}
                <div class="event">
                    <h2>Prochain Match</h2>
                    <div class="bloc-meeting">
                        {% for match in nextmatch|slice(0,2) %}
                            <div class="meeting">
                                <span>{{ match.equipe.name }}</span>
                                <div class="match-card">
                                    <img src="{{ asset('/uploads/logo/logo-fce.svg') }}" alt=""/>
                                    VS
                                    <img src="{{ asset('/uploads/logo/'~match.adversaire.logo.name) }}" alt=""/>
                                </div>
                                <div class="date">
                                    <span class="day">{{ match.matchDate | date('d / m / Y') }} à {{ match.matchDate | date('H : i') }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% elseif nextmatch != null and nextmatch|length == 1 %}
                <div class="event">
                    <h2>Prochain Match</h2>
                    <div class="bloc-meeting ">
                        {% for match in nextmatch|slice(0,1) %}
                            <div class="meeting1seulmatch">
                                <span>{{ match.equipe.name }}</span>
                                <div class="match-card">
                                    <img src="{{ asset('/uploads/logo/logo-fce.svg') }}" alt=""/>
                                    VS
                                    <img src="{{ asset('/uploads/logo/'~match.adversaire.logo.name) }}" alt=""/>
                                </div>
                                <div class="date">
                                    <span class="day">{{ match.matchDate | date('d / m / Y') }} à {{ match.matchDate | date('H : i') }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>


            {% else %}
                <div class="event">
                    <h2>Prochain Match</h2>
                    <div class="meeting">
                        <p>Aucun match a venir</p>
                    </div>
                    <div class="date">

                    </div>
                </div>
            {% endif %}
        </section>


        <section class="club">
            <div class="desc">
                <h3>Info club</h3>
                <p>
                    Toutes les informations du club sont à retrouver ici. Vous retrouverez prochainement les horaires,
                    calendriers, résultats, photos, reportages...
                </p>
                <p>Comme nous explique le président, notre slogan est bien d'actualité : nous allons envoyer tous
                    ensemble Mérignac Arlac vers une nouvelle dimension !!!
                </p>
            </div>
            <div class="carousel-container">
                <div class="arrow" id="arrow-left">
                    <svg
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                            stroke="currentColor"
                            stroke-width="2"
                            fill="none"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                    >
                        <polyline points="15 18 9 12 15 6"></polyline>
                    </svg>
                </div>
                <div class="carousel">

                    {% for info in articleInfo %}
                        <a href="{{ path('article_slug',{'slug': info.slug}) }}" class="">
                            {% if info.photoEnAvant != null %}
                                <img src="{{ asset('uploads/'~ info.photoEnAvant.name ) }}" alt=""/>
                            {% endif %}

                            <div class="link title">
                                <h3>{{ info.titre }}</h3>
                                <span class="date">{{ info.createdDate|date('d / m / Y') }}</span>
                            </div>
                        </a>
                    {% endfor %}
                </div>
                <div class="arrow" id="arrow-right">
                    <svg
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                            stroke="currentColor"
                            stroke-width="2"
                            fill="none"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                    >
                        <polyline points="9 18 15 12 9 6"></polyline>
                    </svg>
                </div>
            </div>
        </section>


        <script src="{{ asset('js/mainscript.js') }}"></script>
        <section class="blog">
            {% for cat in category %}
            {% if loop.last %}

            <div class="articlemain">
                {% elseif loop.index == 1 or loop.index == 4  or loop.index == 5 or loop.index == 8 or loop.index == 9 or loop.index == 12 or loop.index == 13 or loop.index == 17 or loop.index == 18 %}
                <div class="articlemain70">
                    {% else %}
                    <div class="articlemain30">
                        {% endif %}
                        <script>ArticleCategory('{{ cat.name }}', {{ cat.id }});</script>
                        <a class="lientarticle" id="lienArticle{{ cat.id }}"
                           href="{{ path('article_slug',{'slug' : '$' }) }}">
                            <div class="article-large">
                                <h2>{{ cat.name }}</h2>
                                <div class="img-article-cadre">
                                    <img id="imagearticlecat{{ cat.id }}" src="" alt=""/>
                                </div>
                                <div class="link title">
                                    <h3 id="titre{{ cat.id }}"></h3>
                                    <span id="date{{ cat.id }}" class="date"></span>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>


        <section class="logos">
            <div class="autoplay">
                <img src="{{ asset('logoPartenaire/BACKSTAGES NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/BLOCSTOP NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/CLUB VIP NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/DECATHLON NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/ECF NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/FAYAT NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/FIAT NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/FITNES PARK NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/GROUPAMA NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/IBIS HOTEL NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/LEBIHAN NOIR.svg') }}">
                <img src="{{ asset('logoPartenaire/LP PROMOTION NOIR.svg') }}">
            </div>
        </section>


    </main>
    {% include 'include/mainFooter.html.twig' %}




    <script>
        function carousel() {
            const leftArrow = document.querySelector("#arrow-left")
            const rightArrow = document.querySelector("#arrow-right")
            const carousel = document.querySelector(".carousel")
            const length = 500

            leftArrow.onclick = () => {
                carousel.scrollLeft -= length
                console.log('coucou')
            }
            rightArrow.onclick = () => {
                carousel.scrollLeft += length
            }
        }

        carousel()
    </script>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/_article.css') }}">
    <link rel="stylesheet" href="{{ asset('css/login.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_index.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_legals.css') }}">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}